### ISSUE TITLE
Add Docker Container

### ISSUE THREAD

**Issue by ThunderHen** [Davilarek/TekstoLibre#3]
Hello I would like to have a docker container, so I can set up a local instance easily. Thanks

**Comment by Davilarek** [comment]
Hello,
I'll add a `Dockerfile` after remaking the local server to make the server handle API fetching instead of client side.

**Comment by ThunderHen** [comment]
Thank you

**Comment by Davilarek** [comment]
can you see if this `Dockerfile` on https://github.com/Davilarek/TekstoLibre/tree/add-dockerfile works? can't test right now.

**Comment by Davilarek** [comment]
Should be working. Feel free to submit another issue if you find one
